# Generated by Django 5.0.2 on 2024-02-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('atividade_principal', models.CharField(max_length=200)),
                ('numero_endereco', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('municipio', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
    ]
